[PoC RESULT]: False
[PoC MSG]:
============================== Run PoC ==============================
------------------------------ Standard Output ------------------------------
Testing against Django installed in '/workspace/django/django' with up to 64 processes
System check identified no issues (0 silenced).

------------------------------ Standard Error ------------------------------
Creating test database for alias 'default'...

======================================================================
ERROR: test_template_detail_path_traversal (admin_docs.test_views.AdminDocViewDefaultEngineOnly) (path='/etc/passwd')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/django/tests/admin_docs/test_views.py", line 150, in test_template_detail_path_traversal
    response = self.client.get(
  File "/workspace/django/django/test/client.py", line 742, in get
    response = super().get(path, data=data, secure=secure, **extra)
  File "/workspace/django/django/test/client.py", line 396, in get
    return self.generic('GET', path, secure=secure, **{
  File "/workspace/django/django/test/client.py", line 473, in generic
    return self.request(**r)
  File "/workspace/django/django/test/client.py", line 719, in request
    self.check_exception(response)
  File "/workspace/django/django/test/client.py", line 580, in check_exception
    raise exc_value
  File "/workspace/django/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/workspace/django/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/workspace/django/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/workspace/django/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/workspace/django/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/workspace/django/django/contrib/admindocs/views.py", line 43, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/workspace/django/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/workspace/django/django/views/generic/base.py", line 159, in get
    context = self.get_context_data(**kwargs)
  File "/workspace/django/django/contrib/admindocs/views.py", line 337, in get_context_data
    if abs_tmpl.is_relative_to(abs_dir):
AttributeError: 'PosixPath' object has no attribute 'is_relative_to'

======================================================================
ERROR: test_template_detail_path_traversal (admin_docs.test_views.AdminDocViewDefaultEngineOnly) (path='../passwd')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/django/tests/admin_docs/test_views.py", line 150, in test_template_detail_path_traversal
    response = self.client.get(
  File "/workspace/django/django/test/client.py", line 742, in get
    response = super().get(path, data=data, secure=secure, **extra)
  File "/workspace/django/django/test/client.py", line 396, in get
    return self.generic('GET', path, secure=secure, **{
  File "/workspace/django/django/test/client.py", line 473, in generic
    return self.request(**r)
  File "/workspace/django/django/test/client.py", line 719, in request
    self.check_exception(response)
  File "/workspace/django/django/test/client.py", line 580, in check_exception
    raise exc_value
  File "/workspace/django/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/workspace/django/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/workspace/django/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/workspace/django/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/workspace/django/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/workspace/django/django/contrib/admindocs/views.py", line 43, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/workspace/django/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/workspace/django/django/views/generic/base.py", line 159, in get
    context = self.get_context_data(**kwargs)
  File "/workspace/django/django/contrib/admindocs/views.py", line 337, in get_context_data
    if abs_tmpl.is_relative_to(abs_dir):
AttributeError: 'PosixPath' object has no attribute 'is_relative_to'

----------------------------------------------------------------------
Ran 1 test in 0.063s

FAILED (errors=2)
Destroying test database for alias 'default'...

------------------------------ Finish Evaluation ------------------------------


[UnitTest RESULT]: None
[UnitTest MSG]:
 None

[Validation TYPE]: validation_fail