[PoC RESULT]: False
[PoC MSG]:
============================== Run PoC ==============================
------------------------------ Standard Output ------------------------------
[1m============================= test session starts ==============================[0m
platform linux -- Python 3.8.20, pytest-8.3.5, pluggy-1.5.0 -- /workspace/PoC_env/CVE-2023-6831/bin/python
cachedir: .pytest_cache
rootdir: /workspace/mlflow
configfile: pytest.ini
plugins: cov-5.0.0, anyio-4.5.2, timeout-2.3.1, localserver-0.5.0
timeout: 1200.0s
timeout method: signal
timeout func_only: False
[1mcollecting ... [0mcollected 26 items

tests/server/test_handlers.py::test_delete_artifact_mlflow_artifacts_throws_for_malicious_path[/path] [31mFAILED | MEM 5.3/251.6 GB | DISK 966.4/5038.6 GB[0m[31m [  3%][0m
tests/server/test_handlers.py::test_delete_artifact_mlflow_artifacts_throws_for_malicious_path[path/../to/file] [31mFAILED | MEM 5.3/251.6 GB | DISK 966.4/5038.6 GB[0m[31m [  7%][0m
tests/server/test_handlers.py::test_delete_artifact_mlflow_artifacts_throws_for_malicious_path[/etc/passwd] [31mFAILED | MEM 5.3/251.6 GB | DISK 966.4/5038.6 GB[0m[31m [ 11%][0m
tests/server/test_handlers.py::test_delete_artifact_mlflow_artifacts_throws_for_malicious_path[/etc/passwd%00.jpg] [31mFAILED | MEM 5.3/251.6 GB | DISK 966.4/5038.6 GB[0m[31m [ 15%][0m
tests/server/test_handlers.py::test_delete_artifact_mlflow_artifacts_throws_for_malicious_path[/file://etc/passwd] [31mFAILED | MEM 5.3/251.6 GB | DISK 966.4/5038.6 GB[0m[31m [ 19%][0m
tests/server/test_handlers.py::test_delete_artifact_mlflow_artifacts_throws_for_malicious_path[%2E%2E%2F%2E%2E%2Fpath] [31mFAILED | MEM 5.3/251.6 GB | DISK 966.4/5038.6 GB[0m[31m [ 23%][0m
tests/store/artifact/test_http_artifact_repo.py::test_list_artifacts_malicious_path[/tmp/path] [32mPASSED | MEM 5.3/251.6 GB | DISK 966.4/5038.6 GB[0m[31m [ 26%][0m
tests/store/artifact/test_http_artifact_repo.py::test_list_artifacts_malicious_path[../../path] [32mPASSED | MEM 5.3/251.6 GB | DISK 966.4/5038.6 GB[0m[31m [ 30%][0m
tests/store/artifact/test_http_artifact_repo.py::test_list_artifacts_malicious_path[%2E%2E%2Fpath] [32mPASSED | MEM 5.3/251.6 GB | DISK 966.4/5038.6 GB[0m[31m [ 34%][0m
tests/utils/test_uri.py::test_validate_path_is_safe_bad[/path] [32mPASSED | MEM 5.3/251.6 GB | DISK 966.4/5038.6 GB[0m[31m [ 38%][0m
tests/utils/test_uri.py::test_validate_path_is_safe_bad[../path] [32mPASSED | MEM 5.3/251.6 GB | DISK 966.4/5038.6 GB[0m[31m [ 42%][0m
tests/utils/test_uri.py::test_validate_path_is_safe_bad[../../path] [32mPASSED | MEM 5.3/251.6 GB | DISK 966.4/5038.6 GB[0m[31m [ 46%][0m
tests/utils/test_uri.py::test_validate_path_is_safe_bad[./../path] [32mPASSED | MEM 5.3/251.6 GB | DISK 966.4/5038.6 GB[0m[31m [ 50%][0m
tests/utils/test_uri.py::test_validate_path_is_safe_bad[path/../to/file] [31mFAILED | MEM 5.3/251.6 GB | DISK 966.4/5038.6 GB[0m[31m [ 53%][0m
tests/utils/test_uri.py::test_validate_path_is_safe_bad[path/../../to/file] [32mPASSED | MEM 5.3/251.6 GB | DISK 966.4/5038.6 GB[0m[31m [ 57%][0m
tests/utils/test_uri.py::test_validate_path_is_safe_bad[file://a#/..//tmp] [32mPASSED | MEM 5.3/251.6 GB | DISK 966.4/5038.6 GB[0m[31m [ 61%][0m
tests/utils/test_uri.py::test_validate_path_is_safe_bad[file://a%23/..//tmp/] [32mPASSED | MEM 5.3/251.6 GB | DISK 966.4/5038.6 GB[0m[31m [ 65%][0m
tests/utils/test_uri.py::test_validate_path_is_safe_bad[/etc/passwd] [32mPASSED | MEM 5.3/251.6 GB | DISK 966.4/5038.6 GB[0m[31m [ 69%][0m
tests/utils/test_uri.py::test_validate_path_is_safe_bad[/etc/passwd%00.jpg] [32mPASSED | MEM 5.3/251.6 GB | DISK 966.4/5038.6 GB[0m[31m [ 73%][0m
tests/utils/test_uri.py::test_validate_path_is_safe_bad[/etc/passwd%00.html] [32mPASSED | MEM 5.3/251.6 GB | DISK 966.4/5038.6 GB[0m[31m [ 76%][0m
tests/utils/test_uri.py::test_validate_path_is_safe_bad[/etc/passwd%00.txt] [32mPASSED | MEM 5.3/251.6 GB | DISK 966.4/5038.6 GB[0m[31m [ 80%][0m
tests/utils/test_uri.py::test_validate_path_is_safe_bad[/etc/passwd%00.php] [32mPASSED | MEM 5.3/251.6 GB | DISK 966.4/5038.6 GB[0m[31m [ 84%][0m
tests/utils/test_uri.py::test_validate_path_is_safe_bad[/etc/passwd%00.asp] [32mPASSED | MEM 5.3/251.6 GB | DISK 966.4/5038.6 GB[0m[31m [ 88%][0m
tests/utils/test_uri.py::test_validate_path_is_safe_bad[/file://etc/passwd] [32mPASSED | MEM 5.3/251.6 GB | DISK 966.4/5038.6 GB[0m[31m [ 92%][0m
tests/utils/test_uri.py::test_validate_path_is_safe_bad[%2E%2E%2Fpath] [32mPASSED | MEM 5.3/251.6 GB | DISK 966.4/5038.6 GB[0m[31m [ 96%][0m
tests/utils/test_uri.py::test_validate_path_is_safe_bad[%2E%2E%2F%2E%2E%2Fpath] [32mPASSED | MEM 5.3/251.6 GB | DISK 966.4/5038.6 GB[0m[31m [100%][0m

=================================== FAILURES ===================================
[31m[1m____ test_delete_artifact_mlflow_artifacts_throws_for_malicious_path[/path] ____[0m

enable_serve_artifacts = None, path = '/path'

    [0m[37m@pytest[39;49;00m.mark.parametrize([90m[39;49;00m
        [33m"[39;49;00m[33mpath[39;49;00m[33m"[39;49;00m,[90m[39;49;00m
        [[90m[39;49;00m
            [33m"[39;49;00m[33m/path[39;49;00m[33m"[39;49;00m,[90m[39;49;00m
            [33m"[39;49;00m[33mpath/../to/file[39;49;00m[33m"[39;49;00m,[90m[39;49;00m
            [33m"[39;49;00m[33m/etc/passwd[39;49;00m[33m"[39;49;00m,[90m[39;49;00m
            [33m"[39;49;00m[33m/etc/passwd[39;49;00m[33m%[39;49;00m[33m00.jpg[39;49;00m[33m"[39;49;00m,[90m[39;49;00m
            [33m"[39;49;00m[33m/file://etc/passwd[39;49;00m[33m"[39;49;00m,[90m[39;49;00m
            [33m"[39;49;00m[33m%2E[39;49;00m[33m%2E[39;49;00m[33m%2F[39;49;00m[33m%2E[39;49;00m[33m%2E[39;49;00m[33m%2F[39;49;00m[33mpath[39;49;00m[33m"[39;49;00m,[90m[39;49;00m
        ],[90m[39;49;00m
    )[90m[39;49;00m
    [94mdef[39;49;00m[90m [39;49;00m[92mtest_delete_artifact_mlflow_artifacts_throws_for_malicious_path[39;49;00m(enable_serve_artifacts, path):[90m[39;49;00m
        response = _delete_artifact_mlflow_artifacts(path)[90m[39;49;00m
        [94massert[39;49;00m response.status_code == [94m400[39;49;00m[90m[39;49;00m
        json_response = json.loads(response.get_data())[90m[39;49;00m
        [94massert[39;49;00m json_response[[33m"[39;49;00m[33merror_code[39;49;00m[33m"[39;49;00m] == ErrorCode.Name(INVALID_PARAMETER_VALUE)[90m[39;49;00m
>       [94massert[39;49;00m json_response[[33m"[39;49;00m[33mmessage[39;49;00m[33m"[39;49;00m] == [33m"[39;49;00m[33mInvalid path[39;49;00m[33m"[39;49;00m[90m[39;49;00m
[1m[31mE       AssertionError: assert 'Invalid path: /path' == 'Invalid path'[0m
[1m[31mE         [0m
[1m[31mE         - Invalid path[0m
[1m[31mE         + Invalid path: /path[0m
[1m[31mE         ?             +++++++[0m

enable_serve_artifacts = None
json_response = {'error_code': 'INVALID_PARAMETER_VALUE', 'message': 'Invalid path: /path'}
path       = '/path'
response   = <Response 75 bytes [400 BAD REQUEST]>

[1m[31mtests/server/test_handlers.py[0m:804: AssertionError
[31m[1m_ test_delete_artifact_mlflow_artifacts_throws_for_malicious_path[path/../to/file] _[0m

enable_serve_artifacts = None, path = 'path/../to/file'

    [0m[37m@pytest[39;49;00m.mark.parametrize([90m[39;49;00m
        [33m"[39;49;00m[33mpath[39;49;00m[33m"[39;49;00m,[90m[39;49;00m
        [[90m[39;49;00m
            [33m"[39;49;00m[33m/path[39;49;00m[33m"[39;49;00m,[90m[39;49;00m
            [33m"[39;49;00m[33mpath/../to/file[39;49;00m[33m"[39;49;00m,[90m[39;49;00m
            [33m"[39;49;00m[33m/etc/passwd[39;49;00m[33m"[39;49;00m,[90m[39;49;00m
            [33m"[39;49;00m[33m/etc/passwd[39;49;00m[33m%[39;49;00m[33m00.jpg[39;49;00m[33m"[39;49;00m,[90m[39;49;00m
            [33m"[39;49;00m[33m/file://etc/passwd[39;49;00m[33m"[39;49;00m,[90m[39;49;00m
            [33m"[39;49;00m[33m%2E[39;49;00m[33m%2E[39;49;00m[33m%2F[39;49;00m[33m%2E[39;49;00m[33m%2E[39;49;00m[33m%2F[39;49;00m[33mpath[39;49;00m[33m"[39;49;00m,[90m[39;49;00m
        ],[90m[39;49;00m
    )[90m[39;49;00m
    [94mdef[39;49;00m[90m [39;49;00m[92mtest_delete_artifact_mlflow_artifacts_throws_for_malicious_path[39;49;00m(enable_serve_artifacts, path):[90m[39;49;00m
>       response = _delete_artifact_mlflow_artifacts(path)[90m[39;49;00m

enable_serve_artifacts = None
path       = 'path/../to/file'

[1m[31mtests/server/test_handlers.py[0m:800: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[1m[31mmlflow/server/handlers.py[0m:497: in wrapper
    [0m[94mreturn[39;49;00m func(*args, **kwargs)[90m[39;49;00m
        args       = ('path/../to/file',)
        func       = <function _delete_artifact_mlflow_artifacts at 0x7fc6e771ec10>
        kwargs     = {}
[1m[31mmlflow/server/handlers.py[0m:519: in wrapper
    [0m[94mreturn[39;49;00m func(*args, **kwargs)[90m[39;49;00m
        args       = ('path/../to/file',)
        func       = <function _delete_artifact_mlflow_artifacts at 0x7fc6e771eb80>
        kwargs     = {}
[1m[31mmlflow/server/handlers.py[0m:1961: in _delete_artifact_mlflow_artifacts
    [0m_get_request_message(DeleteArtifact())[90m[39;49;00m
        artifact_path = 'path/../to/file'
[1m[31mmlflow/server/handlers.py[0m:413: in _get_request_message
    [0m[94mif[39;49;00m flask_request.method == [33m"[39;49;00m[33mGET[39;49;00m[33m"[39;49;00m [95mand[39;49;00m [96mlen[39;49;00m(flask_request.query_string) > [94m0[39;49;00m:[90m[39;49;00m
        flask_request = <LocalProxy unbound>
        parser     = <module 'querystring_parser.parser' from '/workspace/PoC_env/CVE-2023-6831/lib/python3.8/site-packages/querystring_parser/parser.py'>
        request_message = 
        schema     = None
[1m[31m../PoC_env/CVE-2023-6831/lib/python3.8/site-packages/werkzeug/local.py[0m:318: in __get__
    [0mobj = instance._get_current_object()[90m[39;49;00m
        instance   = <LocalProxy unbound>
        owner      = <class 'werkzeug.local.LocalProxy'>
        self       = proxy __getattr__
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    [0m[94mdef[39;49;00m[90m [39;49;00m[92m_get_current_object[39;49;00m() -> T:[90m[39;49;00m
        [94mtry[39;49;00m:[90m[39;49;00m
            obj = local.get()[90m[39;49;00m
        [94mexcept[39;49;00m [96mLookupError[39;49;00m:[90m[39;49;00m
>           [94mraise[39;49;00m [96mRuntimeError[39;49;00m(unbound_message) [94mfrom[39;49;00m[90m [39;49;00m[94mNone[39;49;00m[90m[39;49;00m
[1m[31mE           RuntimeError: Working outside of request context.[0m
[1m[31mE           [0m
[1m[31mE           This typically means that you attempted to use functionality that needed[0m
[1m[31mE           an active HTTP request. Consult the documentation on testing for[0m
[1m[31mE           information about how to avoid this problem.[0m

get_name   = operator.attrgetter('request')
local      = <ContextVar name='flask.request_ctx' at 0x7fc6e7ac33b0>
unbound_message = 'Working outside of request context.\n\nThis typically means that you attempted to use functionality that needed\nan active HTTP request. Consult the documentation on testing for\ninformation about how to avoid this problem.'

[1m[31m../PoC_env/CVE-2023-6831/lib/python3.8/site-packages/werkzeug/local.py[0m:519: RuntimeError
[31m[1m_ test_delete_artifact_mlflow_artifacts_throws_for_malicious_path[/etc/passwd] _[0m

enable_serve_artifacts = None, path = '/etc/passwd'

    [0m[37m@pytest[39;49;00m.mark.parametrize([90m[39;49;00m
        [33m"[39;49;00m[33mpath[39;49;00m[33m"[39;49;00m,[90m[39;49;00m
        [[90m[39;49;00m
            [33m"[39;49;00m[33m/path[39;49;00m[33m"[39;49;00m,[90m[39;49;00m
            [33m"[39;49;00m[33mpath/../to/file[39;49;00m[33m"[39;49;00m,[90m[39;49;00m
            [33m"[39;49;00m[33m/etc/passwd[39;49;00m[33m"[39;49;00m,[90m[39;49;00m
            [33m"[39;49;00m[33m/etc/passwd[39;49;00m[33m%[39;49;00m[33m00.jpg[39;49;00m[33m"[39;49;00m,[90m[39;49;00m
            [33m"[39;49;00m[33m/file://etc/passwd[39;49;00m[33m"[39;49;00m,[90m[39;49;00m
            [33m"[39;49;00m[33m%2E[39;49;00m[33m%2E[39;49;00m[33m%2F[39;49;00m[33m%2E[39;49;00m[33m%2E[39;49;00m[33m%2F[39;49;00m[33mpath[39;49;00m[33m"[39;49;00m,[90m[39;49;00m
        ],[90m[39;49;00m
    )[90m[39;49;00m
    [94mdef[39;49;00m[90m [39;49;00m[92mtest_delete_artifact_mlflow_artifacts_throws_for_malicious_path[39;49;00m(enable_serve_artifacts, path):[90m[39;49;00m
        response = _delete_artifact_mlflow_artifacts(path)[90m[39;49;00m
        [94massert[39;49;00m response.status_code == [94m400[39;49;00m[90m[39;49;00m
        json_response = json.loads(response.get_data())[90m[39;49;00m
        [94massert[39;49;00m json_response[[33m"[39;49;00m[33merror_code[39;49;00m[33m"[39;49;00m] == ErrorCode.Name(INVALID_PARAMETER_VALUE)[90m[39;49;00m
>       [94massert[39;49;00m json_response[[33m"[39;49;00m[33mmessage[39;49;00m[33m"[39;49;00m] == [33m"[39;49;00m[33mInvalid path[39;49;00m[33m"[39;49;00m[90m[39;49;00m
[1m[31mE       AssertionError: assert 'Invalid path: /etc/passwd' == 'Invalid path'[0m
[1m[31mE         [0m
[1m[31mE         - Invalid path[0m
[1m[31mE         + Invalid path: /etc/passwd[0m

enable_serve_artifacts = None
json_response = {'error_code': 'INVALID_PARAMETER_VALUE', 'message': 'Invalid path: /etc/passwd'}
path       = '/etc/passwd'
response   = <Response 81 bytes [400 BAD REQUEST]>

[1m[31mtests/server/test_handlers.py[0m:804: AssertionError
[31m[1m_ test_delete_artifact_mlflow_artifacts_throws_for_malicious_path[/etc/passwd%00.jpg] _[0m

enable_serve_artifacts = None, path = '/etc/passwd%00.jpg'

    [0m[37m@pytest[39;49;00m.mark.parametrize([90m[39;49;00m
        [33m"[39;49;00m[33mpath[39;49;00m[33m"[39;49;00m,[90m[39;49;00m
        [[90m[39;49;00m
            [33m"[39;49;00m[33m/path[39;49;00m[33m"[39;49;00m,[90m[39;49;00m
            [33m"[39;49;00m[33mpath/../to/file[39;49;00m[33m"[39;49;00m,[90m[39;49;00m
            [33m"[39;49;00m[33m/etc/passwd[39;49;00m[33m"[39;49;00m,[90m[39;49;00m
            [33m"[39;49;00m[33m/etc/passwd[39;49;00m[33m%[39;49;00m[33m00.jpg[39;49;00m[33m"[39;49;00m,[90m[39;49;00m
            [33m"[39;49;00m[33m/file://etc/passwd[39;49;00m[33m"[39;49;00m,[90m[39;49;00m
            [33m"[39;49;00m[33m%2E[39;49;00m[33m%2E[39;49;00m[33m%2F[39;49;00m[33m%2E[39;49;00m[33m%2E[39;49;00m[33m%2F[39;49;00m[33mpath[39;49;00m[33m"[39;49;00m,[90m[39;49;00m
        ],[90m[39;49;00m
    )[90m[39;49;00m
    [94mdef[39;49;00m[90m [39;49;00m[92mtest_delete_artifact_mlflow_artifacts_throws_for_malicious_path[39;49;00m(enable_serve_artifacts, path):[90m[39;49;00m
        response = _delete_artifact_mlflow_artifacts(path)[90m[39;49;00m
        [94massert[39;49;00m response.status_code == [94m400[39;49;00m[90m[39;49;00m
        json_response = json.loads(response.get_data())[90m[39;49;00m
        [94massert[39;49;00m json_response[[33m"[39;49;00m[33merror_code[39;49;00m[33m"[39;49;00m] == ErrorCode.Name(INVALID_PARAMETER_VALUE)[90m[39;49;00m
>       [94massert[39;49;00m json_response[[33m"[39;49;00m[33mmessage[39;49;00m[33m"[39;49;00m] == [33m"[39;49;00m[33mInvalid path[39;49;00m[33m"[39;49;00m[90m[39;49;00m
[1m[31mE       AssertionError: assert 'Invalid path...passwd%00.jpg' == 'Invalid path'[0m
[1m[31mE         [0m
[1m[31mE         - Invalid path[0m
[1m[31mE         + Invalid path: /etc/passwd%00.jpg[0m

enable_serve_artifacts = None
json_response = {'error_code': 'INVALID_PARAMETER_VALUE', 'message': 'Invalid path: /etc/passwd%00.jpg'}
path       = '/etc/passwd%00.jpg'
response   = <Response 88 bytes [400 BAD REQUEST]>

[1m[31mtests/server/test_handlers.py[0m:804: AssertionError
[31m[1m_ test_delete_artifact_mlflow_artifacts_throws_for_malicious_path[/file://etc/passwd] _[0m

enable_serve_artifacts = None, path = '/file://etc/passwd'

    [0m[37m@pytest[39;49;00m.mark.parametrize([90m[39;49;00m
        [33m"[39;49;00m[33mpath[39;49;00m[33m"[39;49;00m,[90m[39;49;00m
        [[90m[39;49;00m
            [33m"[39;49;00m[33m/path[39;49;00m[33m"[39;49;00m,[90m[39;49;00m
            [33m"[39;49;00m[33mpath/../to/file[39;49;00m[33m"[39;49;00m,[90m[39;49;00m
            [33m"[39;49;00m[33m/etc/passwd[39;49;00m[33m"[39;49;00m,[90m[39;49;00m
            [33m"[39;49;00m[33m/etc/passwd[39;49;00m[33m%[39;49;00m[33m00.jpg[39;49;00m[33m"[39;49;00m,[90m[39;49;00m
            [33m"[39;49;00m[33m/file://etc/passwd[39;49;00m[33m"[39;49;00m,[90m[39;49;00m
            [33m"[39;49;00m[33m%2E[39;49;00m[33m%2E[39;49;00m[33m%2F[39;49;00m[33m%2E[39;49;00m[33m%2E[39;49;00m[33m%2F[39;49;00m[33mpath[39;49;00m[33m"[39;49;00m,[90m[39;49;00m
        ],[90m[39;49;00m
    )[90m[39;49;00m
    [94mdef[39;49;00m[90m [39;49;00m[92mtest_delete_artifact_mlflow_artifacts_throws_for_malicious_path[39;49;00m(enable_serve_artifacts, path):[90m[39;49;00m
        response = _delete_artifact_mlflow_artifacts(path)[90m[39;49;00m
        [94massert[39;49;00m response.status_code == [94m400[39;49;00m[90m[39;49;00m
        json_response = json.loads(response.get_data())[90m[39;49;00m
        [94massert[39;49;00m json_response[[33m"[39;49;00m[33merror_code[39;49;00m[33m"[39;49;00m] == ErrorCode.Name(INVALID_PARAMETER_VALUE)[90m[39;49;00m
>       [94massert[39;49;00m json_response[[33m"[39;49;00m[33mmessage[39;49;00m[33m"[39;49;00m] == [33m"[39;49;00m[33mInvalid path[39;49;00m[33m"[39;49;00m[90m[39;49;00m
[1m[31mE       AssertionError: assert 'Invalid path...://etc/passwd' == 'Invalid path'[0m
[1m[31mE         [0m
[1m[31mE         - Invalid path[0m
[1m[31mE         + Invalid path: /file://etc/passwd[0m

enable_serve_artifacts = None
json_response = {'error_code': 'INVALID_PARAMETER_VALUE', 'message': 'Invalid path: /file://etc/passwd'}
path       = '/file://etc/passwd'
response   = <Response 88 bytes [400 BAD REQUEST]>

[1m[31mtests/server/test_handlers.py[0m:804: AssertionError
[31m[1m_ test_delete_artifact_mlflow_artifacts_throws_for_malicious_path[%2E%2E%2F%2E%2E%2Fpath] _[0m

enable_serve_artifacts = None, path = '%2E%2E%2F%2E%2E%2Fpath'

    [0m[37m@pytest[39;49;00m.mark.parametrize([90m[39;49;00m
        [33m"[39;49;00m[33mpath[39;49;00m[33m"[39;49;00m,[90m[39;49;00m
        [[90m[39;49;00m
            [33m"[39;49;00m[33m/path[39;49;00m[33m"[39;49;00m,[90m[39;49;00m
            [33m"[39;49;00m[33mpath/../to/file[39;49;00m[33m"[39;49;00m,[90m[39;49;00m
            [33m"[39;49;00m[33m/etc/passwd[39;49;00m[33m"[39;49;00m,[90m[39;49;00m
            [33m"[39;49;00m[33m/etc/passwd[39;49;00m[33m%[39;49;00m[33m00.jpg[39;49;00m[33m"[39;49;00m,[90m[39;49;00m
            [33m"[39;49;00m[33m/file://etc/passwd[39;49;00m[33m"[39;49;00m,[90m[39;49;00m
            [33m"[39;49;00m[33m%2E[39;49;00m[33m%2E[39;49;00m[33m%2F[39;49;00m[33m%2E[39;49;00m[33m%2E[39;49;00m[33m%2F[39;49;00m[33mpath[39;49;00m[33m"[39;49;00m,[90m[39;49;00m
        ],[90m[39;49;00m
    )[90m[39;49;00m
    [94mdef[39;49;00m[90m [39;49;00m[92mtest_delete_artifact_mlflow_artifacts_throws_for_malicious_path[39;49;00m(enable_serve_artifacts, path):[90m[39;49;00m
        response = _delete_artifact_mlflow_artifacts(path)[90m[39;49;00m
        [94massert[39;49;00m response.status_code == [94m400[39;49;00m[90m[39;49;00m
        json_response = json.loads(response.get_data())[90m[39;49;00m
        [94massert[39;49;00m json_response[[33m"[39;49;00m[33merror_code[39;49;00m[33m"[39;49;00m] == ErrorCode.Name(INVALID_PARAMETER_VALUE)[90m[39;49;00m
>       [94massert[39;49;00m json_response[[33m"[39;49;00m[33mmessage[39;49;00m[33m"[39;49;00m] == [33m"[39;49;00m[33mInvalid path[39;49;00m[33m"[39;49;00m[90m[39;49;00m
[1m[31mE       AssertionError: assert 'Invalid path...%2E%2E%2Fpath' == 'Invalid path'[0m
[1m[31mE         [0m
[1m[31mE         - Invalid path[0m
[1m[31mE         + Invalid path: %2E%2E%2F%2E%2E%2Fpath[0m

enable_serve_artifacts = None
json_response = {'error_code': 'INVALID_PARAMETER_VALUE', 'message': 'Invalid path: %2E%2E%2F%2E%2E%2Fpath'}
path       = '%2E%2E%2F%2E%2E%2Fpath'
response   = <Response 92 bytes [400 BAD REQUEST]>

[1m[31mtests/server/test_handlers.py[0m:804: AssertionError
[31m[1m_______________ test_validate_path_is_safe_bad[path/../to/file] ________________[0m

path = 'path/../to/file'

    [0m[37m@pytest[39;49;00m.mark.skipif(is_windows(), reason=[33m"[39;49;00m[33mThis test does not pass on Windows[39;49;00m[33m"[39;49;00m)[90m[39;49;00m
    [37m@pytest[39;49;00m.mark.parametrize([90m[39;49;00m
        [33m"[39;49;00m[33mpath[39;49;00m[33m"[39;49;00m,[90m[39;49;00m
        [[90m[39;49;00m
            [33m"[39;49;00m[33m/path[39;49;00m[33m"[39;49;00m,[90m[39;49;00m
            [33m"[39;49;00m[33m../path[39;49;00m[33m"[39;49;00m,[90m[39;49;00m
            [33m"[39;49;00m[33m../../path[39;49;00m[33m"[39;49;00m,[90m[39;49;00m
            [33m"[39;49;00m[33m./../path[39;49;00m[33m"[39;49;00m,[90m[39;49;00m
            [33m"[39;49;00m[33mpath/../to/file[39;49;00m[33m"[39;49;00m,[90m[39;49;00m
            [33m"[39;49;00m[33mpath/../../to/file[39;49;00m[33m"[39;49;00m,[90m[39;49;00m
            [33m"[39;49;00m[33mfile://a#/..//tmp[39;49;00m[33m"[39;49;00m,[90m[39;49;00m
            [33m"[39;49;00m[33mfile://a[39;49;00m[33m%[39;49;00m[33m23/..//tmp/[39;49;00m[33m"[39;49;00m,[90m[39;49;00m
            [33m"[39;49;00m[33m/etc/passwd[39;49;00m[33m"[39;49;00m,[90m[39;49;00m
            [33m"[39;49;00m[33m/etc/passwd[39;49;00m[33m%[39;49;00m[33m00.jpg[39;49;00m[33m"[39;49;00m,[90m[39;49;00m
            [33m"[39;49;00m[33m/etc/passwd[39;49;00m[33m%[39;49;00m[33m00.html[39;49;00m[33m"[39;49;00m,[90m[39;49;00m
            [33m"[39;49;00m[33m/etc/passwd[39;49;00m[33m%[39;49;00m[33m00.txt[39;49;00m[33m"[39;49;00m,[90m[39;49;00m
            [33m"[39;49;00m[33m/etc/passwd[39;49;00m[33m%[39;49;00m[33m00.php[39;49;00m[33m"[39;49;00m,[90m[39;49;00m
            [33m"[39;49;00m[33m/etc/passwd[39;49;00m[33m%[39;49;00m[33m00.asp[39;49;00m[33m"[39;49;00m,[90m[39;49;00m
            [33m"[39;49;00m[33m/file://etc/passwd[39;49;00m[33m"[39;49;00m,[90m[39;49;00m
            [90m# Encoded paths with '..'[39;49;00m[90m[39;49;00m
            [33m"[39;49;00m[33m%2E[39;49;00m[33m%2E[39;49;00m[33m%2F[39;49;00m[33mpath[39;49;00m[33m"[39;49;00m,[90m[39;49;00m
            [33m"[39;49;00m[33m%2E[39;49;00m[33m%2E[39;49;00m[33m%2F[39;49;00m[33m%2E[39;49;00m[33m%2E[39;49;00m[33m%2F[39;49;00m[33mpath[39;49;00m[33m"[39;49;00m,[90m[39;49;00m
        ],[90m[39;49;00m
    )[90m[39;49;00m
    [94mdef[39;49;00m[90m [39;49;00m[92mtest_validate_path_is_safe_bad[39;49;00m(path):[90m[39;49;00m
        [94mwith[39;49;00m pytest.raises(MlflowException, match=[33m"[39;49;00m[33mInvalid path[39;49;00m[33m"[39;49;00m):[90m[39;49;00m
>           validate_path_is_safe(path)[90m[39;49;00m
[1m[31mE           Failed: DID NOT RAISE <class 'mlflow.exceptions.MlflowException'>[0m

path       = 'path/../to/file'

[1m[31mtests/utils/test_uri.py[0m:780: Failed
============================= slowest 10 durations =============================

(10 durations < 0.005s hidden.  Use -vv to show these durations.)
======================= command to run failed test cases =======================
pytest 'tests/server/test_handlers.py::test_delete_artifact_mlflow_artifacts_throws_for_malicious_path[/path]' 'tests/server/test_handlers.py::test_delete_artifact_mlflow_artifacts_throws_for_malicious_path[path/../to/file]' 'tests/server/test_handlers.py::test_delete_artifact_mlflow_artifacts_throws_for_malicious_path[/etc/passwd]' 'tests/server/test_handlers.py::test_delete_artifact_mlflow_artifacts_throws_for_malicious_path[/etc/passwd%00.jpg]' 'tests/server/test_handlers.py::test_delete_artifact_mlflow_artifacts_throws_for_malicious_path[/file://etc/passwd]' 'tests/server/test_handlers.py::test_delete_artifact_mlflow_artifacts_throws_for_malicious_path[%2E%2E%2F%2E%2E%2Fpath]' 'tests/utils/test_uri.py::test_validate_path_is_safe_bad[path/../to/file]'

[36m[1m=========================== short test summary info ============================[0m
[31mFAILED | MEM 5.3/251.6 GB | DISK 966.4/5038.6 GB[0m tests/server/test_handlers.py::[1mtest_delete_artifact_mlflow_artifacts_throws_for_malicious_path[/path][0m - AssertionError: assert 'Invalid path: /path' == 'Invalid path'
[31mFAILED | MEM 5.3/251.6 GB | DISK 966.4/5038.6 GB[0m tests/server/test_handlers.py::[1mtest_delete_artifact_mlflow_artifacts_throws_for_malicious_path[path/../to/file][0m - RuntimeError: Working outside of request context.
[31mFAILED | MEM 5.3/251.6 GB | DISK 966.4/5038.6 GB[0m tests/server/test_handlers.py::[1mtest_delete_artifact_mlflow_artifacts_throws_for_malicious_path[/etc/passwd][0m - AssertionError: assert 'Invalid path: /etc/passwd' == 'Invalid path'
[31mFAILED | MEM 5.3/251.6 GB | DISK 966.4/5038.6 GB[0m tests/server/test_handlers.py::[1mtest_delete_artifact_mlflow_artifacts_throws_for_malicious_path[/etc/passwd%00.jpg][0m - AssertionError: assert 'Invalid path...passwd%00.jpg' == 'Invalid path'
[31mFAILED | MEM 5.3/251.6 GB | DISK 966.4/5038.6 GB[0m tests/server/test_handlers.py::[1mtest_delete_artifact_mlflow_artifacts_throws_for_malicious_path[/file://etc/passwd][0m - AssertionError: assert 'Invalid path...://etc/passwd' == 'Invalid path'
[31mFAILED | MEM 5.3/251.6 GB | DISK 966.4/5038.6 GB[0m tests/server/test_handlers.py::[1mtest_delete_artifact_mlflow_artifacts_throws_for_malicious_path[%2E%2E%2F%2E%2E%2Fpath][0m - AssertionError: assert 'Invalid path...%2E%2E%2Fpath' == 'Invalid path'
[31mFAILED | MEM 5.3/251.6 GB | DISK 966.4/5038.6 GB[0m tests/utils/test_uri.py::[1mtest_validate_path_is_safe_bad[path/../to/file][0m - Failed: DID NOT RAISE <class 'mlflow.exceptions.MlflowException'>
[31m================== [31m[1m7 failed[0m, [32m19 passed[0m, [33m14 warnings[0m[31m in 0.80s[0m[31m ===================[0m

------------------------------ Finish Evaluation ------------------------------


[UnitTest RESULT]: None
[UnitTest MSG]:
 None

[Validation TYPE]: validation_fail