[PoC RESULT]: False
[PoC MSG]:
============================== Run PoC ==============================
------------------------------ Standard Output ------------------------------
<empty>
------------------------------ Standard Error ------------------------------
E
======================================================================
ERROR: setUpClass (__main__.TestCampPatch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "hand_test.py", line 47, in setUpClass
    raise RuntimeError(
RuntimeError: Server process terminated unexpectedly.
Return code: 1
STDOUT: 
STDERR: Traceback (most recent call last):
  File "server.py", line 26, in <module>
    with open(os.path.join(ROOT, "secret_key.txt")) as in_file:
FileNotFoundError: [Errno 2] No such file or directory: './secret_key.txt'


----------------------------------------------------------------------
Ran 0 tests in 0.561s

FAILED (errors=1)

------------------------------ Finish Evaluation ------------------------------


[UnitTest RESULT]: None
[UnitTest MSG]:
 None

[Validation TYPE]: validation_fail