[PoC RESULT]: False
[PoC MSG]:
============================== Run PoC ==============================
------------------------------ Standard Output ------------------------------
Testing against Django installed in '/workspace/django/django' with up to 64 processes
System check identified no issues (0 silenced).

------------------------------ Standard Error ------------------------------

======================================================================
FAIL: test_extract_function_traversal (utils_tests.test_archive.TestArchiveInvalid) [traversal.tar]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/django/tests/utils_tests/test_archive.py", line 68, in test_extract_function_traversal
    archive.extract(os.path.join(archives_dir, entry), tmpdir)
  File "/root/miniconda3/envs/py_38/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/workspace/django/django/test/testcases.py", line 691, in _assert_raises_or_warns_cm
    yield cm
AssertionError: SuspiciousOperation not raised

======================================================================
FAIL: test_extract_function_traversal (utils_tests.test_archive.TestArchiveInvalid) [traversal_absolute.tar]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/django/tests/utils_tests/test_archive.py", line 68, in test_extract_function_traversal
    archive.extract(os.path.join(archives_dir, entry), tmpdir)
  File "/root/miniconda3/envs/py_38/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/workspace/django/django/test/testcases.py", line 691, in _assert_raises_or_warns_cm
    yield cm
AssertionError: SuspiciousOperation not raised

----------------------------------------------------------------------
Ran 1 test in 0.003s

FAILED (failures=2)

------------------------------ Finish Evaluation ------------------------------


[UnitTest RESULT]: None
[UnitTest MSG]:
 None

[Validation TYPE]: validation_fail