[PoC RESULT]: False
[PoC MSG]:
============================== Run PoC ==============================
------------------------------ Standard Output ------------------------------
<empty>
------------------------------ Standard Error ------------------------------
EEEEE
======================================================================
ERROR: test_update_chuanhu_admin_named_user_empty_admin_list (__main__.TestUpdateChuanhu)
Test a user named 'admin' calling update_chuanhu when admin_list is empty (patched version).
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/miniconda3/envs/py_310/lib/python3.10/unittest/mock.py", line 1376, in patched
    with self.decoration_helper(patched,
  File "/root/miniconda3/envs/py_310/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/root/miniconda3/envs/py_310/lib/python3.10/unittest/mock.py", line 1358, in decoration_helper
    arg = exit_stack.enter_context(patching)
  File "/root/miniconda3/envs/py_310/lib/python3.10/contextlib.py", line 492, in enter_context
    result = _cm_type.__enter__(cm)
  File "/root/miniconda3/envs/py_310/lib/python3.10/unittest/mock.py", line 1447, in __enter__
    original, local = self.get_original()
  File "/root/miniconda3/envs/py_310/lib/python3.10/unittest/mock.py", line 1420, in get_original
    raise AttributeError(
AttributeError: <module 'modules.utils' from '/workspace/chuanhuchatgpt/modules/utils.py'> does not have the attribute 'admin_list'

======================================================================
ERROR: test_update_chuanhu_admin_user_update_failure (__main__.TestUpdateChuanhu)
Test that an ADMIN user calling update_chuanhu fails to update (patched version).
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/miniconda3/envs/py_310/lib/python3.10/unittest/mock.py", line 1376, in patched
    with self.decoration_helper(patched,
  File "/root/miniconda3/envs/py_310/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/root/miniconda3/envs/py_310/lib/python3.10/unittest/mock.py", line 1358, in decoration_helper
    arg = exit_stack.enter_context(patching)
  File "/root/miniconda3/envs/py_310/lib/python3.10/contextlib.py", line 492, in enter_context
    result = _cm_type.__enter__(cm)
  File "/root/miniconda3/envs/py_310/lib/python3.10/unittest/mock.py", line 1447, in __enter__
    original, local = self.get_original()
  File "/root/miniconda3/envs/py_310/lib/python3.10/unittest/mock.py", line 1420, in get_original
    raise AttributeError(
AttributeError: <module 'modules.utils' from '/workspace/chuanhuchatgpt/modules/utils.py'> does not have the attribute 'admin_list'

======================================================================
ERROR: test_update_chuanhu_admin_user_update_success (__main__.TestUpdateChuanhu)
Test that an ADMIN user can successfully update using update_chuanhu (patched version).
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/miniconda3/envs/py_310/lib/python3.10/unittest/mock.py", line 1376, in patched
    with self.decoration_helper(patched,
  File "/root/miniconda3/envs/py_310/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/root/miniconda3/envs/py_310/lib/python3.10/unittest/mock.py", line 1358, in decoration_helper
    arg = exit_stack.enter_context(patching)
  File "/root/miniconda3/envs/py_310/lib/python3.10/contextlib.py", line 492, in enter_context
    result = _cm_type.__enter__(cm)
  File "/root/miniconda3/envs/py_310/lib/python3.10/unittest/mock.py", line 1447, in __enter__
    original, local = self.get_original()
  File "/root/miniconda3/envs/py_310/lib/python3.10/unittest/mock.py", line 1420, in get_original
    raise AttributeError(
AttributeError: <module 'modules.utils' from '/workspace/chuanhuchatgpt/modules/utils.py'> does not have the attribute 'admin_list'

======================================================================
ERROR: test_update_chuanhu_non_admin_user (__main__.TestUpdateChuanhu)
Test a NON-ADMIN user calling update_chuanhu (patched version).
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/miniconda3/envs/py_310/lib/python3.10/unittest/mock.py", line 1376, in patched
    with self.decoration_helper(patched,
  File "/root/miniconda3/envs/py_310/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/root/miniconda3/envs/py_310/lib/python3.10/unittest/mock.py", line 1358, in decoration_helper
    arg = exit_stack.enter_context(patching)
  File "/root/miniconda3/envs/py_310/lib/python3.10/contextlib.py", line 492, in enter_context
    result = _cm_type.__enter__(cm)
  File "/root/miniconda3/envs/py_310/lib/python3.10/unittest/mock.py", line 1447, in __enter__
    original, local = self.get_original()
  File "/root/miniconda3/envs/py_310/lib/python3.10/unittest/mock.py", line 1420, in get_original
    raise AttributeError(
AttributeError: <module 'modules.utils' from '/workspace/chuanhuchatgpt/modules/utils.py'> does not have the attribute 'admin_list'

======================================================================
ERROR: test_update_chuanhu_non_admin_user_empty_admin_list (__main__.TestUpdateChuanhu)
Test a NON-ADMIN user calling update_chuanhu when admin_list is empty (patched version).
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/miniconda3/envs/py_310/lib/python3.10/unittest/mock.py", line 1376, in patched
    with self.decoration_helper(patched,
  File "/root/miniconda3/envs/py_310/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/root/miniconda3/envs/py_310/lib/python3.10/unittest/mock.py", line 1358, in decoration_helper
    arg = exit_stack.enter_context(patching)
  File "/root/miniconda3/envs/py_310/lib/python3.10/contextlib.py", line 492, in enter_context
    result = _cm_type.__enter__(cm)
  File "/root/miniconda3/envs/py_310/lib/python3.10/unittest/mock.py", line 1447, in __enter__
    original, local = self.get_original()
  File "/root/miniconda3/envs/py_310/lib/python3.10/unittest/mock.py", line 1420, in get_original
    raise AttributeError(
AttributeError: <module 'modules.utils' from '/workspace/chuanhuchatgpt/modules/utils.py'> does not have the attribute 'admin_list'

----------------------------------------------------------------------
Ran 5 tests in 0.008s

FAILED (errors=5)

------------------------------ Finish Evaluation ------------------------------


[UnitTest RESULT]: None
[UnitTest MSG]:
 None

[Validation TYPE]: validation_fail