[PoC RESULT]: False
[PoC MSG]:
============================== Run PoC ==============================
------------------------------ Standard Output ------------------------------
--- FAIL: TestFirstFactorSuite (0.00s)
    --- FAIL: TestFirstFactorSuite/TestShouldAuthenticateUserWithEmailAsUsernameInput (0.00s)
        handler_firstfactor.go:61: Unexpected call to *mocks.MockUserProvider.CheckUserPassword([test@example.com hello]) at /workspace/authelia/internal/handlers/handler_firstfactor.go:61 because: 
            expected call at /workspace/authelia/internal/handlers/handler_firstfactor_test.go:289 doesn't match the argument at index 0.
            Got: test@example.com (string)
            Want: is equal to test (string)
        controller.go:251: missing call(s) to *mocks.MockUserProvider.CheckUserPassword(is equal to test (string), is equal to hello (string)) /workspace/authelia/internal/handlers/handler_firstfactor_test.go:289
        controller.go:251: missing call(s) to *mocks.MockStorage.AppendAuthenticationLog(is equal to #0000000000000000 - 0.0.0.0:0<->0.0.0.0:0 - GET http:/// (*middlewares.AutheliaCtx), is equal to {0 2013-02-03 00:00:00 +0000 UTC true false test 1FA {0.0.0.0}  } (model.AuthenticationAttempt)) /workspace/authelia/internal/handlers/handler_firstfactor_test.go:293
        controller.go:251: aborting test due to missing call(s)
    suite.go:234: warning: no tests to run
FAIL
exit status 1
FAIL	github.com/authelia/authelia/v4/internal/handlers	0.036s

------------------------------ Finish Evaluation ------------------------------


[UnitTest RESULT]: None
[UnitTest MSG]:
 None

[Validation TYPE]: validation_fail