[PoC RESULT]: False
[PoC MSG]:
============================== Run PoC ==============================
------------------------------ Standard Output ------------------------------
============================= test session starts ==============================
platform linux -- Python 3.6.13, pytest-7.0.1, pluggy-1.0.0
rootdir: /workspace/python-dbusmock
collected 1 item

tests/test_api.py F                                                      [100%]

=================================== FAILURES ===================================
___________________________ TestTemplates.test_local ___________________________

self = <test_api.TestTemplates testMethod=test_local>

        def test_local(self):
            '''Load a local template *.py file'''
    
            with tempfile.NamedTemporaryFile(prefix='answer_', suffix='.py') as my_template:
                my_template.write(b'''import dbus
    BUS_NAME = 'universe.Ultimate'
    MAIN_OBJ = '/'
    MAIN_IFACE = 'universe.Ultimate'
    SYSTEM_BUS = False
    
    def load(mock, parameters):
        mock.AddMethods(MAIN_IFACE, [('Answer', '', 'i', 'ret = 42')])
    ''')
                my_template.flush()
                (p_mock, dbus_ultimate) = self.spawn_server_template(
                    my_template.name, stdout=subprocess.PIPE)
                self.addCleanup(p_mock.wait)
                self.addCleanup(p_mock.terminate)
                self.addCleanup(p_mock.stdout.close)
    
                # ensure that we don't use/write any .pyc files, they are dangerous
                # in a world-writable directory like /tmp
                self.assertFalse(os.path.exists(my_template.name + 'c'))
                try:
                    from importlib.util import cache_from_source
>                   self.assertFalse(os.path.exists(cache_from_source(my_template.name)))
E                   AssertionError: True is not false

tests/test_api.py:600: AssertionError
=========================== short test summary info ============================
FAILED tests/test_api.py::TestTemplates::test_local - AssertionError: True is...
======================== 1 failed, 2 warnings in 0.44s =========================

------------------------------ Finish Evaluation ------------------------------


[UnitTest RESULT]: None
[UnitTest MSG]:
 None

[Validation TYPE]: validation_fail